[package]
name = "brightness"
version = "0.4.0"
author = "John Gosset <john@gossetx.com>"
description = "Adjust screen brightness"
architecture = "x86_64"

[[file]]
path = "/usr/bin/brightness"
contentFrom = "./brightness"
mode = "0755"
owner = "root"
group = "root"
